msg:
  #请求成功
  10000: 请求成功
  11000: 未知错误
  12000: 请求频率过快
  #用户相关
  20001: 用户名不能为空
  20002: 密码不能为空
  #通用
  80001: 更新主键不能为空
  80002: 缺少必要参数
  80003: 登录已过期，请重新登录
  80004: 请输入正确的手机号
  80005: 验证码错误
  80006: 来源路由不合法
  80007: 分页不能为空
  80008: 账号已被封禁，请联系管理员